### PR TITLE
Update to scheduler to avoid segfault.

### PR DESCRIPTION
**Pull request by ioquatix**
Fixes <https://github.com/ged/ruby-pg/issues/418>.

### CODE REVIEW

**Comment by ioquatix** [comment]
@larskanis can you check this? TY :)

**Comment by larskanis** [comment]
Thank you so much for helping! I'll review it tomorrow. What I wonder about is that ruby shouldn't segfault if I use the scheduler in a wrong way. But the patch to ruby is only about the test scheduler and documentation, which is great and very helpful, but IMHO doesn't fix the problem that ruby core segfaults when misused. Instead it should raise some kind of error.

**Comment by ioquatix** [comment]
The problem is, the scheduler takes a reference to the fiber but does not mark it during GC. It's a tricky problem because marking objects which have been submitted to the kernel is pretty tricky... in this case we keep a separate hash table, but it's not very efficient.

**Comment by ioquatix** [comment]
> What I wonder about is that ruby shouldn't segfault if I use the scheduler in a wrong way

I agree with this but neither does `Thread::Mutex` retain its wait queue. So it's actually the same problem. https://bugs.ruby-lang.org/issues/18818

**Comment by larskanis** [comment]
Thanks for the pointer! That makes the issue much more understandable. Still it's rather unexpected behaviour.

**Comment by larskanis** [comment]
@ioquatix Thank you so much for helping!

**Pull request merged**
